# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'integrator_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from QTDesigner.mplwidget import MplWidget
from qwt.qt.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1353, 983)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(891, 210, 451, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(400, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(4000, 300))
        self.groupBox_4.setObjectName("groupBox_4")
        
        
        #--------------------------------------------------------------
        self.MplWidget = MplWidget(self.groupBox_4)
        self.MplWidget.setObjectName("MplWidget")
        
        self.verticalLayout_CAM = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_CAM.addWidget(self.MplWidget)
        self.verticalLayout.addWidget(self.groupBox_4)
        #--------------------------------------------------------------
        
        
        
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 210, 881, 721))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox.setObjectName("groupBox")
        self.EEG_plot = PlotWidget(self.groupBox)
        self.EEG_plot.setGeometry(QtCore.QRect(10, 30, 851, 261))
        self.EEG_plot.setObjectName("EEG_plot")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.signals_groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.signals_groupBox.setObjectName("signals_groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.signals_groupBox)
        self.verticalLayout_8.setContentsMargins(6, 12, 6, 6)
        self.verticalLayout_8.setSpacing(24)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.BVP_plot = QwtPlot(self.signals_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BVP_plot.sizePolicy().hasHeightForWidth())
        self.BVP_plot.setSizePolicy(sizePolicy)
        self.BVP_plot.setMinimumSize(QtCore.QSize(300, 100))
        self.BVP_plot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BVP_plot.setFrameShadow(QtWidgets.QFrame.Plain)
        #-----------------
        brush = QtGui.QBrush(QtGui.QColor(Qt.black))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.BVP_plot.setCanvasBackground(brush)
        #-----------------
        self.BVP_plot.setObjectName("BVP_plot")
        self.verticalLayout_8.addWidget(self.BVP_plot)
        self.GSR_plot = QwtPlot(self.signals_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GSR_plot.sizePolicy().hasHeightForWidth())
        self.GSR_plot.setSizePolicy(sizePolicy)
        self.GSR_plot.setMinimumSize(QtCore.QSize(300, 100))
        #-----------------
        brush = QtGui.QBrush(QtGui.QColor(Qt.black))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.GSR_plot.setCanvasBackground(brush)
        #-----------------
        self.GSR_plot.setObjectName("GSR_plot")
        self.verticalLayout_8.addWidget(self.GSR_plot)
        self.TMP_plot = QwtPlot(self.signals_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TMP_plot.sizePolicy().hasHeightForWidth())
        self.TMP_plot.setSizePolicy(sizePolicy)
        self.TMP_plot.setMinimumSize(QtCore.QSize(300, 100))
        #-----------------
        brush = QtGui.QBrush(QtGui.QColor(Qt.black))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.TMP_plot.setCanvasBackground(brush)
        #-----------------
        self.TMP_plot.setObjectName("TMP_plot")
        self.verticalLayout_8.addWidget(self.TMP_plot)
        self.verticalLayout_2.addWidget(self.signals_groupBox)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1341, 211))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(220, 16777215))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 29, 201, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.user_btn = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_btn.sizePolicy().hasHeightForWidth())
        self.user_btn.setSizePolicy(sizePolicy)
        self.user_btn.setMinimumSize(QtCore.QSize(70, 20))
        self.user_btn.setMaximumSize(QtCore.QSize(70, 20))
        self.user_btn.setObjectName("user_btn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.user_btn)
        self.loadScript_btn = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadScript_btn.sizePolicy().hasHeightForWidth())
        self.loadScript_btn.setSizePolicy(sizePolicy)
        self.loadScript_btn.setMinimumSize(QtCore.QSize(70, 20))
        self.loadScript_btn.setMaximumSize(QtCore.QSize(70, 20))
        self.loadScript_btn.setObjectName("loadScript_btn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loadScript_btn)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.trigger_btn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.trigger_btn.setMinimumSize(QtCore.QSize(70, 20))
        self.trigger_btn.setMaximumSize(QtCore.QSize(70, 20))
        self.trigger_btn.setObjectName("trigger_btn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.trigger_btn)
        self.IP_textEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.IP_textEdit.setMinimumSize(QtCore.QSize(100, 20))
        self.IP_textEdit.setMaximumSize(QtCore.QSize(100, 20))
        self.IP_textEdit.setObjectName("IP_textEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.IP_textEdit)
        self.PORT_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.PORT_spinBox.setMinimumSize(QtCore.QSize(70, 20))
        self.PORT_spinBox.setMaximumSize(QtCore.QSize(50, 20))
        self.PORT_spinBox.setMinimum(10000)
        self.PORT_spinBox.setMaximum(10099)
        self.PORT_spinBox.setObjectName("PORT_spinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PORT_spinBox)
        self.start_btn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.start_btn.setEnabled(True)
        self.start_btn.setMinimumSize(QtCore.QSize(70, 17))
        self.start_btn.setMaximumSize(QtCore.QSize(70, 17))
        self.start_btn.setObjectName("start_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.start_btn)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.controls_groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.controls_groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.controls_groupBox_2.setMaximumSize(QtCore.QSize(300, 400))
        self.controls_groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.controls_groupBox_2.setObjectName("controls_groupBox_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.controls_groupBox_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.windowsSize_formLayout_5 = QtWidgets.QFormLayout()
        self.windowsSize_formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.windowsSize_formLayout_5.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.windowsSize_formLayout_5.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.windowsSize_formLayout_5.setFormAlignment(QtCore.Qt.AlignCenter)
        self.windowsSize_formLayout_5.setContentsMargins(6, 0, 6, 0)
        self.windowsSize_formLayout_5.setSpacing(6)
        self.windowsSize_formLayout_5.setObjectName("windowsSize_formLayout_5")
        self.butterOrder_label_4 = QtWidgets.QLabel(self.controls_groupBox_2)
        self.butterOrder_label_4.setObjectName("butterOrder_label_4")
        self.windowsSize_formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.butterOrder_label_4)
        self.butterOrder_spinBox = QtWidgets.QSpinBox(self.controls_groupBox_2)
        self.butterOrder_spinBox.setMinimum(5)
        self.butterOrder_spinBox.setMaximum(300)
        self.butterOrder_spinBox.setProperty("value", 5)
        self.butterOrder_spinBox.setObjectName("butterOrder_spinBox")
        self.windowsSize_formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.butterOrder_spinBox)
        self.frequency_label_4 = QtWidgets.QLabel(self.controls_groupBox_2)
        self.frequency_label_4.setObjectName("frequency_label_4")
        self.windowsSize_formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.frequency_label_4)
        self.frequency_comboBox = QtWidgets.QComboBox(self.controls_groupBox_2)
        self.frequency_comboBox.setCurrentText("")
        self.frequency_comboBox.setObjectName("frequency_comboBox")
        self.windowsSize_formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frequency_comboBox)
        self.filtering_label_4 = QtWidgets.QLabel(self.controls_groupBox_2)
        self.filtering_label_4.setObjectName("filtering_label_4")
        self.windowsSize_formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.filtering_label_4)
        self.filtering_comboBox = QtWidgets.QComboBox(self.controls_groupBox_2)
        self.filtering_comboBox.setObjectName("filtering_comboBox")
        self.windowsSize_formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.filtering_comboBox)
        self.Spectrogram_radioButton = QtWidgets.QRadioButton(self.controls_groupBox_2)
        self.Spectrogram_radioButton.setObjectName("Spectrogram_radioButton")
        self.windowsSize_formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Spectrogram_radioButton)
        self.Spectrogram_comboBox = QtWidgets.QComboBox(self.controls_groupBox_2)
        self.Spectrogram_comboBox.setObjectName("Spectrogram_comboBox")
        self.windowsSize_formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Spectrogram_comboBox)
        self.verticalLayout_14.addLayout(self.windowsSize_formLayout_5)
        self.horizontalLayout_2.addWidget(self.controls_groupBox_2)
        self.controls_groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.controls_groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.controls_groupBox.setMaximumSize(QtCore.QSize(300, 400))
        self.controls_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.controls_groupBox.setObjectName("controls_groupBox")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.controls_groupBox)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.windowsSize_formLayout_6 = QtWidgets.QFormLayout()
        self.windowsSize_formLayout_6.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.windowsSize_formLayout_6.setFormAlignment(QtCore.Qt.AlignCenter)
        self.windowsSize_formLayout_6.setContentsMargins(6, 6, 6, 6)
        self.windowsSize_formLayout_6.setSpacing(6)
        self.windowsSize_formLayout_6.setObjectName("windowsSize_formLayout_6")
        self.WindowsSize_label_3 = QtWidgets.QLabel(self.controls_groupBox)
        self.WindowsSize_label_3.setObjectName("WindowsSize_label_3")
        self.windowsSize_formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.WindowsSize_label_3)
        self.EEG_comboBox = QtWidgets.QSpinBox(self.controls_groupBox)
        self.EEG_comboBox.setMinimum(1)
        self.EEG_comboBox.setMaximum(60)
        self.EEG_comboBox.setProperty("value", 6)
        self.EEG_comboBox.setObjectName("EEG_comboBox")
        self.windowsSize_formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.EEG_comboBox)
        self.bvpWindowsSize_label_3 = QtWidgets.QLabel(self.controls_groupBox)
        self.bvpWindowsSize_label_3.setObjectName("bvpWindowsSize_label_3")
        self.windowsSize_formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bvpWindowsSize_label_3)
        self.BVP_comboBox = QtWidgets.QSpinBox(self.controls_groupBox)
        self.BVP_comboBox.setMinimum(5)
        self.BVP_comboBox.setMaximum(300)
        self.BVP_comboBox.setProperty("value", 12)
        self.BVP_comboBox.setObjectName("BVP_comboBox")
        self.windowsSize_formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.BVP_comboBox)
        self.gsrWindowsSize_label_3 = QtWidgets.QLabel(self.controls_groupBox)
        self.gsrWindowsSize_label_3.setObjectName("gsrWindowsSize_label_3")
        self.windowsSize_formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gsrWindowsSize_label_3)
        self.GSR_comboBox = QtWidgets.QSpinBox(self.controls_groupBox)
        self.GSR_comboBox.setMinimum(5)
        self.GSR_comboBox.setMaximum(300)
        self.GSR_comboBox.setProperty("value", 120)
        self.GSR_comboBox.setObjectName("GSR_comboBox")
        self.windowsSize_formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.GSR_comboBox)
        self.tmpWindowsSize_label_3 = QtWidgets.QLabel(self.controls_groupBox)
        self.tmpWindowsSize_label_3.setObjectName("tmpWindowsSize_label_3")
        self.windowsSize_formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.tmpWindowsSize_label_3)
        self.TMP_comboBox = QtWidgets.QSpinBox(self.controls_groupBox)
        self.TMP_comboBox.setMinimum(5)
        self.TMP_comboBox.setMaximum(300)
        self.TMP_comboBox.setProperty("value", 120)
        self.TMP_comboBox.setObjectName("TMP_comboBox")
        self.windowsSize_formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.TMP_comboBox)
        self.label_3 = QtWidgets.QLabel(self.controls_groupBox)
        self.label_3.setObjectName("label_3")
        self.windowsSize_formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.CAM_comboBox = QtWidgets.QSpinBox(self.controls_groupBox)
        self.CAM_comboBox.setMinimum(1)
        self.CAM_comboBox.setMaximum(60)
        self.CAM_comboBox.setProperty("value", 6)
        self.CAM_comboBox.setObjectName("CAM_comboBox")
        self.windowsSize_formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.CAM_comboBox)
        self.verticalLayout_15.addLayout(self.windowsSize_formLayout_6)
        self.horizontalLayout_2.addWidget(self.controls_groupBox)
        self.groupBox_8 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_8.setMinimumSize(QtCore.QSize(100, 0))
        self.groupBox_8.setMaximumSize(QtCore.QSize(110, 16777215))
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_8)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 30, 91, 171))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_16.setContentsMargins(10, 6, 6, 6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.E4_server_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.E4_server_btn.setMinimumSize(QtCore.QSize(70, 20))
        self.E4_server_btn.setMaximumSize(QtCore.QSize(70, 20))
        self.E4_server_btn.setObjectName("E4_server_btn")
        self.verticalLayout_16.addWidget(self.E4_server_btn)
        self.refresh_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.refresh_btn.setMinimumSize(QtCore.QSize(70, 20))
        self.refresh_btn.setMaximumSize(QtCore.QSize(70, 20))
        self.refresh_btn.setObjectName("refresh_btn")
        self.verticalLayout_16.addWidget(self.refresh_btn)
        self.E4_device_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.E4_device_comboBox.setEnabled(True)
        self.E4_device_comboBox.setMinimumSize(QtCore.QSize(70, 20))
        self.E4_device_comboBox.setMaximumSize(QtCore.QSize(70, 20))
        self.E4_device_comboBox.setEditable(False)
        self.E4_device_comboBox.setCurrentText("")
        self.E4_device_comboBox.setIconSize(QtCore.QSize(16, 16))
        self.E4_device_comboBox.setObjectName("E4_device_comboBox")
        self.verticalLayout_16.addWidget(self.E4_device_comboBox)
        self.E4_connect_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.E4_connect_btn.setMinimumSize(QtCore.QSize(70, 0))
        self.E4_connect_btn.setMaximumSize(QtCore.QSize(70, 17))
        self.E4_connect_btn.setObjectName("E4_connect_btn")
        self.verticalLayout_16.addWidget(self.E4_connect_btn)
        self.OpenBCI_connect_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.OpenBCI_connect_btn.setEnabled(True)
        self.OpenBCI_connect_btn.setMinimumSize(QtCore.QSize(70, 20))
        self.OpenBCI_connect_btn.setMaximumSize(QtCore.QSize(70, 20))
        self.OpenBCI_connect_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OpenBCI_connect_btn.setObjectName("OpenBCI_connect_btn")
        self.verticalLayout_16.addWidget(self.OpenBCI_connect_btn)
        self.horizontalLayout_2.addWidget(self.groupBox_8)
        self.log_groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.log_groupBox.setMinimumSize(QtCore.QSize(250, 50))
        self.log_groupBox.setMaximumSize(QtCore.QSize(450, 16777215))
        self.log_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.log_groupBox.setObjectName("log_groupBox")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.log_groupBox)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.LOGGER = QtWidgets.QPlainTextEdit(self.log_groupBox)
        self.LOGGER.setReadOnly(True)
        self.LOGGER.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.LOGGER.setObjectName("LOGGER")
        self.verticalLayout_17.addWidget(self.LOGGER)
        self.horizontalLayout_2.addWidget(self.log_groupBox)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(889, 519, 451, 411))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox_5 = QtWidgets.QGroupBox(self.verticalLayoutWidget_6)
        self.groupBox_5.setObjectName("groupBox_5")
        self.Frequency_plot = PlotWidget(self.groupBox_5)
        self.Frequency_plot.setGeometry(QtCore.QRect(10, 30, 431, 181))
        self.Frequency_plot.setObjectName("Frequency_plot")
        self.EEG_short_plot = PlotWidget(self.groupBox_5)
        self.EEG_short_plot.setGeometry(QtCore.QRect(10, 210, 431, 191))
        self.EEG_short_plot.setObjectName("EEG_short_plot")
        self.verticalLayout_18.addWidget(self.groupBox_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1353, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Image signals"))
        self.groupBox.setTitle(_translate("MainWindow", "EEG signals"))
        self.signals_groupBox.setTitle(_translate("MainWindow", "BVP GSR TMP and ACC signals "))
        self.groupBox_3.setTitle(_translate("MainWindow", "General controls"))
        self.user_btn.setText(_translate("MainWindow", "Set Users"))
        self.loadScript_btn.setText(_translate("MainWindow", "Load Script"))
        self.label_7.setText(_translate("MainWindow", "Initialize Trigger"))
        self.trigger_btn.setText(_translate("MainWindow", "Trigger"))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.controls_groupBox_2.setTitle(_translate("MainWindow", "Filters"))
        self.butterOrder_label_4.setText(_translate("MainWindow", "Butter filter order"))
        self.frequency_label_4.setText(_translate("MainWindow", "EEG Frequency range"))
        self.filtering_label_4.setText(_translate("MainWindow", "EEG Filtering method"))
        self.Spectrogram_radioButton.setText(_translate("MainWindow", "Spectrogram"))
        self.controls_groupBox.setTitle(_translate("MainWindow", "Signals controls"))
        self.WindowsSize_label_3.setText(_translate("MainWindow", "EEG windows size [seconds]"))
        self.bvpWindowsSize_label_3.setText(_translate("MainWindow", "BVP windows size [seconds]"))
        self.gsrWindowsSize_label_3.setText(_translate("MainWindow", "GSR windows size [seconds]"))
        self.tmpWindowsSize_label_3.setText(_translate("MainWindow", "TMP windows size [seconds]"))
        self.label_3.setText(_translate("MainWindow", "CAM windows size [seconds]"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Drivers"))
        self.E4_server_btn.setText(_translate("MainWindow", "E4 link"))
        self.refresh_btn.setText(_translate("MainWindow", "Refresh"))
        self.E4_connect_btn.setText(_translate("MainWindow", "E4"))
        self.OpenBCI_connect_btn.setText(_translate("MainWindow", "OpenBCI"))
        self.log_groupBox.setTitle(_translate("MainWindow", "Log viewer"))
        self.groupBox_5.setTitle(_translate("MainWindow", "EEG signals short view"))
from pyqtgraph import PlotWidget
from qwt import QwtPlot
