# -*- coding: utf-8 -*-
"""
@author: %(Mikel Val Calvo)s
@email: %(mikel1982mail@gmail.com)
@institution: %(Dpto. de Inteligencia Artificial, Universidad Nacional de Educación a Distancia (UNED))
@DOI: 10.5281/zenodo.3727503 
"""
#%%
from PyQt5 import QtCore, QtGui, QtWidgets
from QTDesigner.mplwidget import MplWidget
from qwt.qt.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1347, 975)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(891, 210, 451, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        
        
        
        #--------------------------------------------------------------
        self.MplWidget = MplWidget(self.groupBox_4)
        self.MplWidget.setObjectName("MplWidget")
        
        self.verticalLayout_CAM = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_CAM.addWidget(self.MplWidget)
        self.verticalLayout.addWidget(self.groupBox_4)
        #--------------------------------------------------------------
        
        
        
        
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 210, 881, 721))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox.setObjectName("groupBox")
        self.EEG_plot = PlotWidget(self.groupBox)
        self.EEG_plot.setGeometry(QtCore.QRect(10, 30, 851, 261))
        self.EEG_plot.setObjectName("EEG_plot")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.signals_groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.signals_groupBox.setObjectName("signals_groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.signals_groupBox)
        self.verticalLayout_8.setContentsMargins(6, 12, 6, 6)
        self.verticalLayout_8.setSpacing(24)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.BVP_plot = QwtPlot(self.signals_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BVP_plot.sizePolicy().hasHeightForWidth())
        self.BVP_plot.setSizePolicy(sizePolicy)
        self.BVP_plot.setMinimumSize(QtCore.QSize(300, 100))
        self.BVP_plot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BVP_plot.setFrameShadow(QtWidgets.QFrame.Plain)
        #-----------------
        brush = QtGui.QBrush(QtGui.QColor(Qt.black))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.BVP_plot.setCanvasBackground(brush)
        #-----------------
        self.BVP_plot.setObjectName("BVP_plot")
        self.verticalLayout_8.addWidget(self.BVP_plot)
        self.GSR_plot = QwtPlot(self.signals_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GSR_plot.sizePolicy().hasHeightForWidth())
        self.GSR_plot.setSizePolicy(sizePolicy)
        self.GSR_plot.setMinimumSize(QtCore.QSize(300, 100))
        #-----------------
        brush = QtGui.QBrush(QtGui.QColor(Qt.black))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.GSR_plot.setCanvasBackground(brush)
        #-----------------
        self.GSR_plot.setObjectName("GSR_plot")
        self.verticalLayout_8.addWidget(self.GSR_plot)
        self.TMP_plot = QwtPlot(self.signals_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TMP_plot.sizePolicy().hasHeightForWidth())
        self.TMP_plot.setSizePolicy(sizePolicy)
        self.TMP_plot.setMinimumSize(QtCore.QSize(300, 100))
        #-----------------
        brush = QtGui.QBrush(QtGui.QColor(Qt.black))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.TMP_plot.setCanvasBackground(brush)
        #-----------------
        self.TMP_plot.setObjectName("TMP_plot")
        self.verticalLayout_8.addWidget(self.TMP_plot)
        self.verticalLayout_2.addWidget(self.signals_groupBox)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(889, 519, 451, 411))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox_5 = QtWidgets.QGroupBox(self.verticalLayoutWidget_6)
        self.groupBox_5.setObjectName("groupBox_5")
        self.Frequency_plot = PlotWidget(self.groupBox_5)
        self.Frequency_plot.setGeometry(QtCore.QRect(10, 30, 431, 181))
        self.Frequency_plot.setObjectName("Frequency_plot")
        self.EEG_short_plot = PlotWidget(self.groupBox_5)
        self.EEG_short_plot.setGeometry(QtCore.QRect(10, 210, 431, 191))
        self.EEG_short_plot.setObjectName("EEG_short_plot")
        self.verticalLayout_18.addWidget(self.groupBox_5)
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 0, 251, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.groupBox_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_11.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_11.setObjectName("groupBox_11")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_11)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 29, 221, 161))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.save_bttn = QtWidgets.QPushButton(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_bttn.sizePolicy().hasHeightForWidth())
        self.save_bttn.setSizePolicy(sizePolicy)
        self.save_bttn.setMinimumSize(QtCore.QSize(70, 20))
        self.save_bttn.setMaximumSize(QtCore.QSize(70, 20))
        self.save_bttn.setObjectName("save_bttn")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.save_bttn)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.script_bttn = QtWidgets.QPushButton(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.script_bttn.sizePolicy().hasHeightForWidth())
        self.script_bttn.setSizePolicy(sizePolicy)
        self.script_bttn.setMinimumSize(QtCore.QSize(70, 20))
        self.script_bttn.setMaximumSize(QtCore.QSize(70, 20))
        self.script_bttn.setObjectName("script_bttn")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.script_bttn)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.trigger_bttn = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.trigger_bttn.setMinimumSize(QtCore.QSize(70, 20))
        self.trigger_bttn.setMaximumSize(QtCore.QSize(70, 20))
        self.trigger_bttn.setObjectName("trigger_bttn")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.trigger_bttn)
        self.IP_TextEdit = QtWidgets.QTextEdit(self.formLayoutWidget_3)
        self.IP_TextEdit.setMinimumSize(QtCore.QSize(100, 20))
        self.IP_TextEdit.setMaximumSize(QtCore.QSize(100, 20))
        self.IP_TextEdit.setObjectName("IP_TextEdit")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.IP_TextEdit)
        self.PORT_SpinBox = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.PORT_SpinBox.setMinimumSize(QtCore.QSize(70, 20))
        self.PORT_SpinBox.setMaximumSize(QtCore.QSize(50, 20))
        self.PORT_SpinBox.setMinimum(10000)
        self.PORT_SpinBox.setMaximum(10099)
        self.PORT_SpinBox.setObjectName("PORT_SpinBox")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.PORT_SpinBox)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.start_bttn = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.start_bttn.setEnabled(True)
        self.start_bttn.setMinimumSize(QtCore.QSize(70, 17))
        self.start_bttn.setMaximumSize(QtCore.QSize(70, 17))
        self.start_bttn.setObjectName("start_bttn")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.start_bttn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_16.setGeometry(QtCore.QRect(950, 0, 391, 201))
        self.groupBox_16.setObjectName("groupBox_16")
        self.logger = QtWidgets.QPlainTextEdit(self.groupBox_16)
        self.logger.setGeometry(QtCore.QRect(10, 30, 371, 161))
        self.logger.setReadOnly(True)
        self.logger.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.logger.setObjectName("logger")
        self.controls_groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.controls_groupBox_3.setGeometry(QtCore.QRect(490, 0, 251, 201))
        self.controls_groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.controls_groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.controls_groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.controls_groupBox_3.setObjectName("controls_groupBox_3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.controls_groupBox_3)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.windowsSize_formLayout_7 = QtWidgets.QFormLayout()
        self.windowsSize_formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.windowsSize_formLayout_7.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.windowsSize_formLayout_7.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.windowsSize_formLayout_7.setFormAlignment(QtCore.Qt.AlignCenter)
        self.windowsSize_formLayout_7.setContentsMargins(6, 0, 6, 0)
        self.windowsSize_formLayout_7.setSpacing(6)
        self.windowsSize_formLayout_7.setObjectName("windowsSize_formLayout_7")
        self.butterOrder_label_5 = QtWidgets.QLabel(self.controls_groupBox_3)
        self.butterOrder_label_5.setObjectName("butterOrder_label_5")
        self.windowsSize_formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.butterOrder_label_5)
        self.butterOrder_SpinBox = QtWidgets.QSpinBox(self.controls_groupBox_3)
        self.butterOrder_SpinBox.setMinimum(5)
        self.butterOrder_SpinBox.setMaximum(300)
        self.butterOrder_SpinBox.setProperty("value", 5)
        self.butterOrder_SpinBox.setObjectName("butterOrder_SpinBox")
        self.windowsSize_formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.butterOrder_SpinBox)
        self.frequency_label_5 = QtWidgets.QLabel(self.controls_groupBox_3)
        self.frequency_label_5.setObjectName("frequency_label_5")
        self.windowsSize_formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.frequency_label_5)
        self.frequency_ComboBox = QtWidgets.QComboBox(self.controls_groupBox_3)
        self.frequency_ComboBox.setCurrentText("")
        self.frequency_ComboBox.setObjectName("frequency_ComboBox")
        self.windowsSize_formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frequency_ComboBox)
        self.filtering_label_5 = QtWidgets.QLabel(self.controls_groupBox_3)
        self.filtering_label_5.setObjectName("filtering_label_5")
        self.windowsSize_formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.filtering_label_5)
        self.filtering_ComboBox = QtWidgets.QComboBox(self.controls_groupBox_3)
        self.filtering_ComboBox.setObjectName("filtering_ComboBox")
        self.windowsSize_formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.filtering_ComboBox)
        self.Spectrogram_RadioButton = QtWidgets.QRadioButton(self.controls_groupBox_3)
        self.Spectrogram_RadioButton.setObjectName("Spectrogram_RadioButton")
        self.windowsSize_formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Spectrogram_RadioButton)
        self.Spectrogram_ComboBox = QtWidgets.QComboBox(self.controls_groupBox_3)
        self.Spectrogram_ComboBox.setObjectName("Spectrogram_ComboBox")
        self.windowsSize_formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Spectrogram_ComboBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.windowsSize_formLayout_7.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.verticalLayout_16.addLayout(self.windowsSize_formLayout_7)
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_12.setGeometry(QtCore.QRect(270, 0, 211, 201))
        self.groupBox_12.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_12.setObjectName("groupBox_12")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 30, 171, 71))
        self.groupBox_13.setObjectName("groupBox_13")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_13)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 171, 51))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.E4_server_bttn = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.E4_server_bttn.setMinimumSize(QtCore.QSize(70, 20))
        self.E4_server_bttn.setMaximumSize(QtCore.QSize(70, 20))
        self.E4_server_bttn.setObjectName("E4_server_bttn")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.E4_server_bttn)
        self.refresh_bttn = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.refresh_bttn.setMinimumSize(QtCore.QSize(70, 20))
        self.refresh_bttn.setMaximumSize(QtCore.QSize(70, 20))
        self.refresh_bttn.setObjectName("refresh_bttn")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.refresh_bttn)
        self.E4_device_ComboBox = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.E4_device_ComboBox.setEnabled(True)
        self.E4_device_ComboBox.setMinimumSize(QtCore.QSize(70, 20))
        self.E4_device_ComboBox.setMaximumSize(QtCore.QSize(70, 20))
        self.E4_device_ComboBox.setEditable(False)
        self.E4_device_ComboBox.setCurrentText("")
        self.E4_device_ComboBox.setIconSize(QtCore.QSize(16, 16))
        self.E4_device_ComboBox.setObjectName("E4_device_ComboBox")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.E4_device_ComboBox)
        self.E4_connect_bttn = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.E4_connect_bttn.setMinimumSize(QtCore.QSize(70, 0))
        self.E4_connect_bttn.setMaximumSize(QtCore.QSize(70, 17))
        self.E4_connect_bttn.setObjectName("E4_connect_bttn")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.E4_connect_bttn)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_14.setGeometry(QtCore.QRect(20, 120, 81, 71))
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_14)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 30, 81, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_6.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.OpenBCI_connect_bttn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.OpenBCI_connect_bttn.setEnabled(True)
        self.OpenBCI_connect_bttn.setMinimumSize(QtCore.QSize(70, 20))
        self.OpenBCI_connect_bttn.setMaximumSize(QtCore.QSize(70, 20))
        self.OpenBCI_connect_bttn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OpenBCI_connect_bttn.setObjectName("OpenBCI_connect_bttn")
        self.verticalLayout_6.addWidget(self.OpenBCI_connect_bttn)
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_15.setGeometry(QtCore.QRect(110, 120, 81, 71))
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_15)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 30, 81, 31))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.CAM_connect_bttn = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.CAM_connect_bttn.setEnabled(True)
        self.CAM_connect_bttn.setMinimumSize(QtCore.QSize(70, 20))
        self.CAM_connect_bttn.setMaximumSize(QtCore.QSize(70, 20))
        self.CAM_connect_bttn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CAM_connect_bttn.setObjectName("CAM_connect_bttn")
        self.verticalLayout_7.addWidget(self.CAM_connect_bttn)
        self.controls_groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.controls_groupBox_4.setGeometry(QtCore.QRect(750, 0, 191, 201))
        self.controls_groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.controls_groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.controls_groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.controls_groupBox_4.setObjectName("controls_groupBox_4")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.controls_groupBox_4)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.windowsSize_formLayout_8 = QtWidgets.QFormLayout()
        self.windowsSize_formLayout_8.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.windowsSize_formLayout_8.setFormAlignment(QtCore.Qt.AlignCenter)
        self.windowsSize_formLayout_8.setContentsMargins(6, 6, 6, 6)
        self.windowsSize_formLayout_8.setSpacing(6)
        self.windowsSize_formLayout_8.setObjectName("windowsSize_formLayout_8")
        self.WindowsSize_label_4 = QtWidgets.QLabel(self.controls_groupBox_4)
        self.WindowsSize_label_4.setObjectName("WindowsSize_label_4")
        self.windowsSize_formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.WindowsSize_label_4)
        self.EEG_ComboBox = QtWidgets.QSpinBox(self.controls_groupBox_4)
        self.EEG_ComboBox.setMinimum(1)
        self.EEG_ComboBox.setMaximum(60)
        self.EEG_ComboBox.setProperty("value", 6)
        self.EEG_ComboBox.setObjectName("EEG_ComboBox")
        self.windowsSize_formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.EEG_ComboBox)
        self.bvpWindowsSize_label_4 = QtWidgets.QLabel(self.controls_groupBox_4)
        self.bvpWindowsSize_label_4.setObjectName("bvpWindowsSize_label_4")
        self.windowsSize_formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.bvpWindowsSize_label_4)
        self.BVP_ComboBox = QtWidgets.QSpinBox(self.controls_groupBox_4)
        self.BVP_ComboBox.setMinimum(5)
        self.BVP_ComboBox.setMaximum(300)
        self.BVP_ComboBox.setProperty("value", 12)
        self.BVP_ComboBox.setObjectName("BVP_ComboBox")
        self.windowsSize_formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.BVP_ComboBox)
        self.gsrWindowsSize_label_4 = QtWidgets.QLabel(self.controls_groupBox_4)
        self.gsrWindowsSize_label_4.setObjectName("gsrWindowsSize_label_4")
        self.windowsSize_formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.gsrWindowsSize_label_4)
        self.GSR_ComboBox = QtWidgets.QSpinBox(self.controls_groupBox_4)
        self.GSR_ComboBox.setMinimum(5)
        self.GSR_ComboBox.setMaximum(300)
        self.GSR_ComboBox.setProperty("value", 120)
        self.GSR_ComboBox.setObjectName("GSR_ComboBox")
        self.windowsSize_formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.GSR_ComboBox)
        self.tmpWindowsSize_label_4 = QtWidgets.QLabel(self.controls_groupBox_4)
        self.tmpWindowsSize_label_4.setObjectName("tmpWindowsSize_label_4")
        self.windowsSize_formLayout_8.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.tmpWindowsSize_label_4)
        self.TMP_ComboBox = QtWidgets.QSpinBox(self.controls_groupBox_4)
        self.TMP_ComboBox.setMinimum(5)
        self.TMP_ComboBox.setMaximum(300)
        self.TMP_ComboBox.setProperty("value", 120)
        self.TMP_ComboBox.setObjectName("TMP_ComboBox")
        self.windowsSize_formLayout_8.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.TMP_ComboBox)
        self.label_10 = QtWidgets.QLabel(self.controls_groupBox_4)
        self.label_10.setObjectName("label_10")
        self.windowsSize_formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.CAM_ComboBox = QtWidgets.QSpinBox(self.controls_groupBox_4)
        self.CAM_ComboBox.setMinimum(1)
        self.CAM_ComboBox.setMaximum(60)
        self.CAM_ComboBox.setProperty("value", 6)
        self.CAM_ComboBox.setObjectName("CAM_ComboBox")
        self.windowsSize_formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.CAM_ComboBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.windowsSize_formLayout_8.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.windowsSize_formLayout_8.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.verticalLayout_17.addLayout(self.windowsSize_formLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1347, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Image signals"))
        self.groupBox.setTitle(_translate("MainWindow", "EEG signals"))
        self.signals_groupBox.setTitle(_translate("MainWindow", "BVP GSR TMP and ACC signals "))
        self.groupBox_5.setTitle(_translate("MainWindow", "EEG signals short view"))
        self.groupBox_11.setTitle(_translate("MainWindow", "General controls"))
        self.label_5.setText(_translate("MainWindow", "Save trials to file"))
        self.save_bttn.setText(_translate("MainWindow", "Save"))
        self.label_6.setText(_translate("MainWindow", "Load custom scripts"))
        self.script_bttn.setText(_translate("MainWindow", "Script"))
        self.label_8.setText(_translate("MainWindow", "Initialize Trigger"))
        self.trigger_bttn.setText(_translate("MainWindow", "Trigger"))
        self.label_9.setText(_translate("MainWindow", "Start/stop recordings"))
        self.start_bttn.setText(_translate("MainWindow", "Start"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Log"))
        self.controls_groupBox_3.setTitle(_translate("MainWindow", "Filters"))
        self.butterOrder_label_5.setText(_translate("MainWindow", "Butter filter order"))
        self.frequency_label_5.setText(_translate("MainWindow", "EEG Frequency range"))
        self.filtering_label_5.setText(_translate("MainWindow", "EEG Filtering method"))
        self.Spectrogram_RadioButton.setText(_translate("MainWindow", "Spectrogram"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Drivers"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Empatica E4"))
        self.E4_server_bttn.setText(_translate("MainWindow", "E4 link"))
        self.refresh_bttn.setText(_translate("MainWindow", "Refresh"))
        self.E4_connect_bttn.setText(_translate("MainWindow", "E4"))
        self.groupBox_14.setTitle(_translate("MainWindow", "OpenBCI"))
        self.OpenBCI_connect_bttn.setText(_translate("MainWindow", "OpenBCI"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Camera"))
        self.CAM_connect_bttn.setText(_translate("MainWindow", "CAM"))
        self.controls_groupBox_4.setTitle(_translate("MainWindow", "Signals controls"))
        self.WindowsSize_label_4.setText(_translate("MainWindow", "EEG [seconds]"))
        self.bvpWindowsSize_label_4.setText(_translate("MainWindow", "BVP [seconds]"))
        self.gsrWindowsSize_label_4.setText(_translate("MainWindow", "GSR [seconds]"))
        self.tmpWindowsSize_label_4.setText(_translate("MainWindow", "TMP [seconds]"))
        self.label_10.setText(_translate("MainWindow", "CAM [seconds]"))
from pyqtgraph import PlotWidget
from qwt import QwtPlot
